#!/bin/sh
wget    -P amicorpus/ES2002a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2002a/audio/ES2002a.Mix-Headset.wav
wget    -P amicorpus/ES2002b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2002b/audio/ES2002b.Mix-Headset.wav
wget    -P amicorpus/ES2002c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2002c/audio/ES2002c.Mix-Headset.wav
wget    -P amicorpus/ES2002d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2002d/audio/ES2002d.Mix-Headset.wav
wget    -P amicorpus/ES2003a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2003a/audio/ES2003a.Mix-Headset.wav
wget    -P amicorpus/ES2003b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2003b/audio/ES2003b.Mix-Headset.wav
wget    -P amicorpus/ES2003c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2003c/audio/ES2003c.Mix-Headset.wav
wget    -P amicorpus/ES2003d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2003d/audio/ES2003d.Mix-Headset.wav
wget    -P amicorpus/ES2004a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2004a/audio/ES2004a.Mix-Headset.wav
wget    -P amicorpus/ES2004b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2004b/audio/ES2004b.Mix-Headset.wav
wget    -P amicorpus/ES2004c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2004c/audio/ES2004c.Mix-Headset.wav
wget    -P amicorpus/ES2004d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2004d/audio/ES2004d.Mix-Headset.wav
wget    -P amicorpus/ES2005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2005a/audio/ES2005a.Mix-Headset.wav
wget    -P amicorpus/ES2005b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2005b/audio/ES2005b.Mix-Headset.wav
wget    -P amicorpus/ES2005c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2005c/audio/ES2005c.Mix-Headset.wav
wget    -P amicorpus/ES2005d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2005d/audio/ES2005d.Mix-Headset.wav
wget    -P amicorpus/ES2006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2006a/audio/ES2006a.Mix-Headset.wav
wget    -P amicorpus/ES2006b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2006b/audio/ES2006b.Mix-Headset.wav
wget    -P amicorpus/ES2006c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2006c/audio/ES2006c.Mix-Headset.wav
wget    -P amicorpus/ES2006d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2006d/audio/ES2006d.Mix-Headset.wav
wget    -P amicorpus/ES2007a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2007a/audio/ES2007a.Mix-Headset.wav
wget    -P amicorpus/ES2007b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2007b/audio/ES2007b.Mix-Headset.wav
wget    -P amicorpus/ES2007c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2007c/audio/ES2007c.Mix-Headset.wav
wget    -P amicorpus/ES2007d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2007d/audio/ES2007d.Mix-Headset.wav
wget    -P amicorpus/ES2008a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2008a/audio/ES2008a.Mix-Headset.wav
wget    -P amicorpus/ES2008b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2008b/audio/ES2008b.Mix-Headset.wav
wget    -P amicorpus/ES2008c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2008c/audio/ES2008c.Mix-Headset.wav
wget    -P amicorpus/ES2008d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2008d/audio/ES2008d.Mix-Headset.wav
wget    -P amicorpus/ES2009a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2009a/audio/ES2009a.Mix-Headset.wav
wget    -P amicorpus/ES2009b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2009b/audio/ES2009b.Mix-Headset.wav
wget    -P amicorpus/ES2009c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2009c/audio/ES2009c.Mix-Headset.wav
wget    -P amicorpus/ES2009d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2009d/audio/ES2009d.Mix-Headset.wav
wget    -P amicorpus/ES2010a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2010a/audio/ES2010a.Mix-Headset.wav
wget    -P amicorpus/ES2010b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2010b/audio/ES2010b.Mix-Headset.wav
wget    -P amicorpus/ES2010c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2010c/audio/ES2010c.Mix-Headset.wav
wget    -P amicorpus/ES2010d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2010d/audio/ES2010d.Mix-Headset.wav
wget    -P amicorpus/ES2011a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2011a/audio/ES2011a.Mix-Headset.wav
wget    -P amicorpus/ES2011b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2011b/audio/ES2011b.Mix-Headset.wav
wget    -P amicorpus/ES2011c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2011c/audio/ES2011c.Mix-Headset.wav
wget    -P amicorpus/ES2011d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2011d/audio/ES2011d.Mix-Headset.wav
wget    -P amicorpus/ES2012a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2012a/audio/ES2012a.Mix-Headset.wav
wget    -P amicorpus/ES2012b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2012b/audio/ES2012b.Mix-Headset.wav
wget    -P amicorpus/ES2012c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2012c/audio/ES2012c.Mix-Headset.wav
wget    -P amicorpus/ES2012d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2012d/audio/ES2012d.Mix-Headset.wav
wget    -P amicorpus/ES2013a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2013a/audio/ES2013a.Mix-Headset.wav
wget    -P amicorpus/ES2013b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2013b/audio/ES2013b.Mix-Headset.wav
wget    -P amicorpus/ES2013c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2013c/audio/ES2013c.Mix-Headset.wav
wget    -P amicorpus/ES2013d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2013d/audio/ES2013d.Mix-Headset.wav
wget    -P amicorpus/ES2014a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2014a/audio/ES2014a.Mix-Headset.wav
wget    -P amicorpus/ES2014b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2014b/audio/ES2014b.Mix-Headset.wav
wget    -P amicorpus/ES2014c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2014c/audio/ES2014c.Mix-Headset.wav
wget    -P amicorpus/ES2014d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2014d/audio/ES2014d.Mix-Headset.wav
wget    -P amicorpus/ES2015a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2015a/audio/ES2015a.Mix-Headset.wav
wget    -P amicorpus/ES2015b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2015b/audio/ES2015b.Mix-Headset.wav
wget    -P amicorpus/ES2015c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2015c/audio/ES2015c.Mix-Headset.wav
wget    -P amicorpus/ES2015d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2015d/audio/ES2015d.Mix-Headset.wav
wget    -P amicorpus/ES2016a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2016a/audio/ES2016a.Mix-Headset.wav
wget    -P amicorpus/ES2016b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2016b/audio/ES2016b.Mix-Headset.wav
wget    -P amicorpus/ES2016c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2016c/audio/ES2016c.Mix-Headset.wav
wget    -P amicorpus/ES2016d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/ES2016d/audio/ES2016d.Mix-Headset.wav
wget    -P amicorpus/IS1000a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1000a/audio/IS1000a.Mix-Headset.wav
wget    -P amicorpus/IS1000b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1000b/audio/IS1000b.Mix-Headset.wav
wget    -P amicorpus/IS1000c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1000c/audio/IS1000c.Mix-Headset.wav
wget    -P amicorpus/IS1000d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1000d/audio/IS1000d.Mix-Headset.wav
wget    -P amicorpus/IS1001a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1001a/audio/IS1001a.Mix-Headset.wav
wget    -P amicorpus/IS1001b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1001b/audio/IS1001b.Mix-Headset.wav
wget    -P amicorpus/IS1001c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1001c/audio/IS1001c.Mix-Headset.wav
wget    -P amicorpus/IS1001d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1001d/audio/IS1001d.Mix-Headset.wav
wget    -P amicorpus/IS1002b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1002b/audio/IS1002b.Mix-Headset.wav
wget    -P amicorpus/IS1002c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1002c/audio/IS1002c.Mix-Headset.wav
wget    -P amicorpus/IS1002d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1002d/audio/IS1002d.Mix-Headset.wav
wget    -P amicorpus/IS1003a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1003a/audio/IS1003a.Mix-Headset.wav
wget    -P amicorpus/IS1003b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1003b/audio/IS1003b.Mix-Headset.wav
wget    -P amicorpus/IS1003c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1003c/audio/IS1003c.Mix-Headset.wav
wget    -P amicorpus/IS1003d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1003d/audio/IS1003d.Mix-Headset.wav
wget    -P amicorpus/IS1004a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1004a/audio/IS1004a.Mix-Headset.wav
wget    -P amicorpus/IS1004b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1004b/audio/IS1004b.Mix-Headset.wav
wget    -P amicorpus/IS1004c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1004c/audio/IS1004c.Mix-Headset.wav
wget    -P amicorpus/IS1004d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1004d/audio/IS1004d.Mix-Headset.wav
wget    -P amicorpus/IS1005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1005a/audio/IS1005a.Mix-Headset.wav
wget    -P amicorpus/IS1005b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1005b/audio/IS1005b.Mix-Headset.wav
wget    -P amicorpus/IS1005c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1005c/audio/IS1005c.Mix-Headset.wav
wget    -P amicorpus/IS1006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1006a/audio/IS1006a.Mix-Headset.wav
wget    -P amicorpus/IS1006b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1006b/audio/IS1006b.Mix-Headset.wav
wget    -P amicorpus/IS1006c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1006c/audio/IS1006c.Mix-Headset.wav
wget    -P amicorpus/IS1006d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1006d/audio/IS1006d.Mix-Headset.wav
wget    -P amicorpus/IS1007a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1007a/audio/IS1007a.Mix-Headset.wav
wget    -P amicorpus/IS1007b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1007b/audio/IS1007b.Mix-Headset.wav
wget    -P amicorpus/IS1007c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1007c/audio/IS1007c.Mix-Headset.wav
wget    -P amicorpus/IS1007d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1007d/audio/IS1007d.Mix-Headset.wav
wget    -P amicorpus/IS1008a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1008a/audio/IS1008a.Mix-Headset.wav
wget    -P amicorpus/IS1008b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1008b/audio/IS1008b.Mix-Headset.wav
wget    -P amicorpus/IS1008c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1008c/audio/IS1008c.Mix-Headset.wav
wget    -P amicorpus/IS1008d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1008d/audio/IS1008d.Mix-Headset.wav
wget    -P amicorpus/IS1009a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1009a/audio/IS1009a.Mix-Headset.wav
wget    -P amicorpus/IS1009b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1009b/audio/IS1009b.Mix-Headset.wav
wget    -P amicorpus/IS1009c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1009c/audio/IS1009c.Mix-Headset.wav
wget    -P amicorpus/IS1009d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IS1009d/audio/IS1009d.Mix-Headset.wav
wget    -P amicorpus/TS3003a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3003a/audio/TS3003a.Mix-Headset.wav
wget    -P amicorpus/TS3003b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3003b/audio/TS3003b.Mix-Headset.wav
wget    -P amicorpus/TS3003c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3003c/audio/TS3003c.Mix-Headset.wav
wget    -P amicorpus/TS3003d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3003d/audio/TS3003d.Mix-Headset.wav
wget    -P amicorpus/TS3004a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3004a/audio/TS3004a.Mix-Headset.wav
wget    -P amicorpus/TS3004b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3004b/audio/TS3004b.Mix-Headset.wav
wget    -P amicorpus/TS3004c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3004c/audio/TS3004c.Mix-Headset.wav
wget    -P amicorpus/TS3004d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3004d/audio/TS3004d.Mix-Headset.wav
wget    -P amicorpus/TS3005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005a/audio/TS3005a.Mix-Headset.wav
wget    -P amicorpus/TS3005b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005b/audio/TS3005b.Mix-Headset.wav
wget    -P amicorpus/TS3005c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005c/audio/TS3005c.Mix-Headset.wav
wget    -P amicorpus/TS3005d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3005d/audio/TS3005d.Mix-Headset.wav
wget    -P amicorpus/TS3006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006a/audio/TS3006a.Mix-Headset.wav
wget    -P amicorpus/TS3006b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006b/audio/TS3006b.Mix-Headset.wav
wget    -P amicorpus/TS3006c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006c/audio/TS3006c.Mix-Headset.wav
wget    -P amicorpus/TS3006d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3006d/audio/TS3006d.Mix-Headset.wav
wget    -P amicorpus/TS3007a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007a/audio/TS3007a.Mix-Headset.wav
wget    -P amicorpus/TS3007b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007b/audio/TS3007b.Mix-Headset.wav
wget    -P amicorpus/TS3007c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007c/audio/TS3007c.Mix-Headset.wav
wget    -P amicorpus/TS3007d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3007d/audio/TS3007d.Mix-Headset.wav
wget    -P amicorpus/TS3008a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008a/audio/TS3008a.Mix-Headset.wav
wget    -P amicorpus/TS3008b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008b/audio/TS3008b.Mix-Headset.wav
wget    -P amicorpus/TS3008c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008c/audio/TS3008c.Mix-Headset.wav
wget    -P amicorpus/TS3008d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3008d/audio/TS3008d.Mix-Headset.wav
wget    -P amicorpus/TS3009a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009a/audio/TS3009a.Mix-Headset.wav
wget    -P amicorpus/TS3009b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009b/audio/TS3009b.Mix-Headset.wav
wget    -P amicorpus/TS3009c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009c/audio/TS3009c.Mix-Headset.wav
wget    -P amicorpus/TS3009d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3009d/audio/TS3009d.Mix-Headset.wav
wget    -P amicorpus/TS3010a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010a/audio/TS3010a.Mix-Headset.wav
wget    -P amicorpus/TS3010b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010b/audio/TS3010b.Mix-Headset.wav
wget    -P amicorpus/TS3010c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010c/audio/TS3010c.Mix-Headset.wav
wget    -P amicorpus/TS3010d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3010d/audio/TS3010d.Mix-Headset.wav
wget    -P amicorpus/TS3011a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011a/audio/TS3011a.Mix-Headset.wav
wget    -P amicorpus/TS3011b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011b/audio/TS3011b.Mix-Headset.wav
wget    -P amicorpus/TS3011c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011c/audio/TS3011c.Mix-Headset.wav
wget    -P amicorpus/TS3011d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3011d/audio/TS3011d.Mix-Headset.wav
wget    -P amicorpus/TS3012a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012a/audio/TS3012a.Mix-Headset.wav
wget    -P amicorpus/TS3012b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012b/audio/TS3012b.Mix-Headset.wav
wget    -P amicorpus/TS3012c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012c/audio/TS3012c.Mix-Headset.wav
wget    -P amicorpus/TS3012d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/TS3012d/audio/TS3012d.Mix-Headset.wav
wget    -P amicorpus/EN2001a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001a/audio/EN2001a.Mix-Headset.wav
wget    -P amicorpus/EN2001b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001b/audio/EN2001b.Mix-Headset.wav
wget    -P amicorpus/EN2001d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001d/audio/EN2001d.Mix-Headset.wav
wget    -P amicorpus/EN2001e/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2001e/audio/EN2001e.Mix-Headset.wav
wget    -P amicorpus/EN2002a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002a/audio/EN2002a.Mix-Headset.wav
wget    -P amicorpus/EN2002b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002b/audio/EN2002b.Mix-Headset.wav
wget    -P amicorpus/EN2002c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002c/audio/EN2002c.Mix-Headset.wav
wget    -P amicorpus/EN2002d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2002d/audio/EN2002d.Mix-Headset.wav
wget    -P amicorpus/EN2003a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2003a/audio/EN2003a.Mix-Headset.wav
wget    -P amicorpus/EN2004a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2004a/audio/EN2004a.Mix-Headset.wav
wget    -P amicorpus/EN2005a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2005a/audio/EN2005a.Mix-Headset.wav
wget    -P amicorpus/EN2006a/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006a/audio/EN2006a.Mix-Headset.wav
wget    -P amicorpus/EN2006b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2006b/audio/EN2006b.Mix-Headset.wav
wget    -P amicorpus/EN2009b/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009b/audio/EN2009b.Mix-Headset.wav
wget    -P amicorpus/EN2009c/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009c/audio/EN2009c.Mix-Headset.wav
wget    -P amicorpus/EN2009d/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/EN2009d/audio/EN2009d.Mix-Headset.wav
wget    -P amicorpus/IB4001/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4001/audio/IB4001.Mix-Headset.wav
wget    -P amicorpus/IB4002/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4002/audio/IB4002.Mix-Headset.wav
wget    -P amicorpus/IB4003/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4003/audio/IB4003.Mix-Headset.wav
wget    -P amicorpus/IB4004/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4004/audio/IB4004.Mix-Headset.wav
wget    -P amicorpus/IB4005/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4005/audio/IB4005.Mix-Headset.wav
wget    -P amicorpus/IB4010/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4010/audio/IB4010.Mix-Headset.wav
wget    -P amicorpus/IB4011/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IB4011/audio/IB4011.Mix-Headset.wav
wget    -P amicorpus/IN1001/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1001/audio/IN1001.Mix-Headset.wav
wget    -P amicorpus/IN1002/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1002/audio/IN1002.Mix-Headset.wav
wget    -P amicorpus/IN1005/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1005/audio/IN1005.Mix-Headset.wav
wget    -P amicorpus/IN1007/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1007/audio/IN1007.Mix-Headset.wav
wget    -P amicorpus/IN1008/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1008/audio/IN1008.Mix-Headset.wav
wget    -P amicorpus/IN1009/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1009/audio/IN1009.Mix-Headset.wav
wget    -P amicorpus/IN1012/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1012/audio/IN1012.Mix-Headset.wav
wget    -P amicorpus/IN1013/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1013/audio/IN1013.Mix-Headset.wav
wget    -P amicorpus/IN1014/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1014/audio/IN1014.Mix-Headset.wav
wget    -P amicorpus/IN1016/audio https://groups.inf.ed.ac.uk/ami/AMICorpusMirror//amicorpus/IN1016/audio/IN1016.Mix-Headset.wav
wget https://groups.inf.ed.ac.uk/ami/download/temp/amiBuild-22147-Tue-Jul-26-2022.manifest.txt
wget https://groups.inf.ed.ac.uk/ami/download/temp/../CCBY4.0.txt
